
const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宠物领养管理",
                        "menuJump":"列表",
                        "tableName":"chongwulingyang"
                    },
					{
					    "buttons":[
					        "查看",
					        "审核",
					        "删除"
					    ],
					    "menu":"宠物领养审核管理",
					    "menuJump":"列表",
					    "tableName":"chongwulingyangshenhe"
					}
                ],
                "menu":"宠物领养管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宠物认领管理",
                        "menuJump":"列表",
                        "tableName":"chongwurenling"
                    },
					{
					    "buttons":[
					        "查看",
					        "审核",
					        "删除"
					    ],
					    "menu":"宠物认领审核管理",
					    "menuJump":"列表",
					    "tableName":"chongwurenlingshenhe"
					}
                ],
                "menu":"宠物认领管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教学视频管理",
                        "menuJump":"列表",
                        "tableName":"jiaoxueshipin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"教学视频留言管理",
                        "menuJump":"列表",
                        "tableName":"jiaoxueshipinLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"教学视频收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiaoxueshipinCollection"
                    }
                ],
                "menu":"教学视频管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"感谢信管理",
			            "menuJump":"列表",
			            "tableName":"ganxiexin"
			        }
			    ],
			    "menu":"感谢信管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"宠物类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryChongwulingyang"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"视频类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJiaoxueshipin"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"宠物领养管理",
	                    "menuJump":"列表",
	                    "tableName":"chongwulingyang"
	                },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"宠物领养审核管理",
					    "menuJump":"列表",
					    "tableName":"chongwulingyangshenhe"
					}
	            ],
	            "menu":"宠物领养管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"宠物认领管理",
	                    "menuJump":"列表",
	                    "tableName":"chongwurenling"
	                },
					{
					    "buttons":[
					        "查看",
					        "审核",
	                        "删除"
					    ],
					    "menu":"宠物认领审核管理",
					    "menuJump":"列表",
					    "tableName":"chongwurenlingshenhe"
					}
	            ],
	            "menu":"宠物认领管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"教学视频管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaoxueshipin"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"教学视频留言管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaoxueshipinLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"教学视频收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaoxueshipinCollection"
	                }
	            ],
	            "menu":"教学视频管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"感谢信管理",
			            "menuJump":"列表",
			            "tableName":"ganxiexin"
			        }
			    ],
			    "menu":"感谢信管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
